use anyhow::Result;
use std::io::Write;

pub const VERBS: &str = include_str!("../../assets/imperatives.txt");
pub const BLACKLIST: &str = include_str!("../../assets/imperatives_blacklist.txt");

pub fn generate<W: Write>(file: &mut W) -> Result<()> {
    writeln!(
        file,
        "// This file is @generated by `cargo dev generate` ({})",
        file!().replace('\\', "/")
    )?;
    writeln!(file)?;

    let en_stemmer = rust_stemmers::Stemmer::create(rust_stemmers::Algorithm::English);
    let words: multimap::MultiMap<_, _> = parse_wordlist(VERBS)
        .map(|s| (en_stemmer.stem(s).into_owned(), s))
        .collect();

    let mut sorted_words: Vec<_> = words.iter_all().collect();
    sorted_words.sort_unstable();
    let sorted_words = sorted_words;
    for (stem, words) in sorted_words {
        let mut words = words.clone();
        words.sort_unstable();
        let words = words;
        writeln!(
            file,
            "pub(crate) static {}_STEM: phf::Set<&'static str> = ",
            stem.to_uppercase(),
        )?;
        let mut builder = phf_codegen::Set::new();
        for word in words {
            builder.entry(word);
        }
        let codegenned = builder.build();
        writeln!(file, "{}", codegenned)?;
        writeln!(file, ";")?;
        writeln!(file)?;
    }

    let mut stems: Vec<_> = words.keys().collect();
    stems.sort_unstable();
    let stems = stems;
    writeln!(
        file,
        "pub(crate) static IMPERATIVES: phf::Map<&'static str, &phf::Set<&'static str>> = "
    )?;
    let mut builder = phf_codegen::Map::new();
    for stem in stems {
        let value = format!("&{}_stem", stem).to_uppercase();
        builder.entry(stem.as_str(), &value);
    }
    let codegenned = builder.build();
    writeln!(file, "{}", codegenned)?;
    writeln!(file, ";")?;

    let mut blacklist: Vec<_> = parse_wordlist(BLACKLIST).collect();
    blacklist.sort_unstable();
    let blacklist = blacklist;
    writeln!(
        file,
        "pub(crate) static BLACKLIST: phf::Set<&'static str> = "
    )?;
    let mut builder = phf_codegen::Set::new();
    for word in blacklist {
        builder.entry(word);
    }
    let codegenned = builder.build();
    writeln!(file, "{}", codegenned)?;
    writeln!(file, ";")?;
    Ok(())
}

fn parse_wordlist(raw: &str) -> impl Iterator<Item = &str> {
    raw.lines()
        .map(|s| s.split('#').next().expect("always at least one").trim())
        .filter(|s| !s.is_empty())
}

pub(crate) fn main() -> Result<()> {
    let mut content = vec![];
    generate(&mut content)?;
    let content = String::from_utf8(content)?;
    if let Ok(content) = codegenrs::rustfmt(content, None) {
        let mut file = std::fs::File::create("src/wordlist_codegen.rs")?;
        file.write_all(content.as_bytes())?;
        Ok(())
    } else {
        anyhow::bail!("rustfmt failed");
    }
}
